
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * records.java
 *
 * Created on Jan,2018
 */
/**
 *
 * @author mradulrathore
 */
public class records extends javax.swing.JFrame {

    Connection con;
    Statement st;
    ResultSet rs;

    /**
     * Creates new form records
     */
    public records() {
        initComponents();
        data();
    }

    void data() {
        try {
            Class.forName("java.sql.DriverManager");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/coachingc", "root", "admin123");
            st = (Statement) con.createStatement();
            String q = "select * from coaching;";
            rs = st.executeQuery(q);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Connection Time" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cleabt = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        searbtn = new javax.swing.JButton();
        addrebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adn = new javax.swing.JTextField();
        stnm = new javax.swing.JTextField();
        fnm = new javax.swing.JTextField();
        cl = new javax.swing.JTextField();
        mn = new javax.swing.JTextField();
        fs = new javax.swing.JTextField();
        sub = new javax.swing.JTextField();
        updtbtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        disbtn = new javax.swing.JButton();
        dispall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cleabt.setText("Clear");
        cleabt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleabtActionPerformed(evt);
            }
        });

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        searbtn.setText("Search");
        searbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searbtnActionPerformed(evt);
            }
        });

        addrebtn.setText("Add Record");
        addrebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrebtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Student's Name");

        jLabel1.setText("Admission No.");

        jLabel3.setText("Father's Name");

        jLabel4.setText("Class");

        jLabel5.setText("Mobile No.");

        jLabel6.setText("Fees");

        jLabel7.setText("Subjects");

        updtbtn.setText("Update");
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });

        delbtn.setText("Delete");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        disbtn.setText("Display");
        disbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disbtnActionPerformed(evt);
            }
        });

        dispall.setText("Display All");
        dispall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addrebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(disbtn)
                                .addGap(18, 18, 18)
                                .addComponent(dispall)
                                .addGap(20, 20, 20)
                                .addComponent(searbtn)))
                        .addGap(18, 18, 18)
                        .addComponent(updtbtn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stnm, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(fnm, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(cl, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(mn, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(fs, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(sub, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(adn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(delbtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cleabt)
                        .addGap(18, 18, 18)
                        .addComponent(exitbtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addrebtn)
                    .addComponent(disbtn)
                    .addComponent(searbtn)
                    .addComponent(dispall)
                    .addComponent(updtbtn)
                    .addComponent(delbtn))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleabt)
                    .addComponent(exitbtn))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleabtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleabtActionPerformed
        // coding for clear button
        adn.setText("");
        stnm.setText("");
        fnm.setText("");
        cl.setText("");
        mn.setText("");
        fs.setText("");
        sub.setText("");
        adn.requestFocus();
}//GEN-LAST:event_cleabtActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // coding for exit button
        JOptionPane.showMessageDialog(null, "Are you sure you want to exit?");
        System.exit(0);
}//GEN-LAST:event_exitbtnActionPerformed

    private void searbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searbtnActionPerformed
        // coding for search button
        try {
            String txt = JOptionPane.showInputDialog("Enter Admission Number to search");
            String q = "select * from coaching where admno=" + txt + ";";
            ResultSet r = st.executeQuery(q);
            if (r.next()) {
                adn.setText(r.getString(1));
                stnm.setText(r.getString(2));
                fnm.setText(r.getString(3));
                cl.setText(r.getString(4));
                mn.setText(r.getString(5));
                fs.setText(r.getString(6));
                sub.setText(r.getString(7));
            } 
            else {
                JOptionPane.showMessageDialog(rootPane, "No such record found");
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Searching not found" + e.getMessage());
        }
}//GEN-LAST:event_searbtnActionPerformed

    private void addrebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrebtnActionPerformed
        // coding for opening the add record window
        this.setVisible(false);
        new insert().setVisible(true);
}//GEN-LAST:event_addrebtnActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed
        // coding for update button
        int x = JOptionPane.showConfirmDialog(rootPane, "Do you want updation of record Yes or No");
        if (x == JOptionPane.YES_OPTION) {
            try {
                String q = "update coaching set studentnm='" + stnm.getText() + "',fathernm='" + fnm.getText() + "',class='" + cl.getText() + "',mobileno='" + mn.getText() + "',fees='" + fs.getText() + "',subjects='" + sub.getText() + "' where admno=" + adn.getText() + ";";
                st.executeUpdate(q);
                JOptionPane.showMessageDialog(null, "Record successfully updated");
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error in table updation");
            }
        }
        adn.setText("");
        stnm.setText("");
        fnm.setText("");
        cl.setText("");
        mn.setText("");
        fs.setText("");
        sub.setText("");
}//GEN-LAST:event_updtbtnActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // coding for delete button
        String txt;
        try {
            int ans = JOptionPane.showConfirmDialog(rootPane, "Do you want to delete a record?");
            if (ans == JOptionPane.YES_OPTION) {
                txt = JOptionPane.showInputDialog(null, "Enter Admission Number for deletion of record", "Delete", 2);
                String q = "select * from coaching where admno=" + txt + ";";
                ResultSet r = st.executeQuery(q);
                if (r.next()) {
                    adn.setText(r.getString(1));
                    stnm.setText(r.getString(2));
                    fnm.setText(r.getString(3));
                    cl.setText(r.getString(4));
                    mn.setText(r.getString(5));
                    fs.setText(r.getString(6));
                    sub.setText(r.getString(7));
                    ans = JOptionPane.showConfirmDialog(this, "Do you want to delete this record?");
                    if (ans == JOptionPane.YES_OPTION) {
                        q = "delete from coaching where admno=" + txt + ";";
                        st.executeUpdate(q);
                        JOptionPane.showMessageDialog(null, "Record deleted");
                    } 
                    else {
                        JOptionPane.showMessageDialog(null, "Deleting process incomplete");
                    }
                }

            }

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in Record Deletion" + e.getMessage());
        }
        adn.setText("");
        stnm.setText("");
        fnm.setText("");
        cl.setText("");
        mn.setText("");
        fs.setText("");
        sub.setText("");

}//GEN-LAST:event_delbtnActionPerformed

    private void disbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disbtnActionPerformed
        // coding for opening display window
        this.setVisible(false);
        new Display().setVisible(true);
}//GEN-LAST:event_disbtnActionPerformed

    private void dispallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispallActionPerformed
        //coding for opening display all window
        this.setVisible(false);
        new DisplayAll().setVisible(true);
}//GEN-LAST:event_dispallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addrebtn;
    private javax.swing.JTextField adn;
    private javax.swing.JTextField cl;
    private javax.swing.JButton cleabt;
    private javax.swing.JButton delbtn;
    private javax.swing.JButton disbtn;
    private javax.swing.JButton dispall;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField fnm;
    private javax.swing.JTextField fs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mn;
    private javax.swing.JButton searbtn;
    private javax.swing.JTextField stnm;
    private javax.swing.JTextField sub;
    private javax.swing.JButton updtbtn;
    // End of variables declaration//GEN-END:variables

}
